name: prettier
version: '1.9.2'
summary: Prettier is an opinionated code formatter
description: |
  Prettier is an opinionated code formatter. It enforces a consistent style
  by parsing your code and re-printing it with its own rules that take the
  maximum line length into account, wrapping code when necessary.

grade: devel
confinement: strict

apps:
  prettier:
    command: bin/prettier
    plugs: [home]

parts:
  prettier:
    source: git://github.com/prettier/prettier.git
    source-tag: '1.9.2'
    plugin: nodejs
    node-engine: '8.9.3'
